apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicejs-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicejs-b
  template:
    metadata:
      labels:
        app: servicejs-b
        version: "200"
    spec:
      containers:
      - name: servicejs-b
        image: abnerstelmastchuk/externalapi:2.1.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
---

apiVersion: v1
kind: Service
metadata:
  name: servicejs-b
spec:
  selector:
    app: servicejs-b
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer # Ou ClusterIP, NodePort, conforme necessário
