apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicejs-c
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicejs-c
  template:
    metadata:
      labels:
        app: servicejs-c
        version: "503"
    spec:
      containers:
      - name: servicejs-c
        image: abnerstelmastchuk/externalapi:2.2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3200
---

apiVersion: v1
kind: Service
metadata:
  name: servicejs-c
spec:
  selector:
    app: servicejs-c
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3200
  type: LoadBalancer # Ou ClusterIP, NodePort, conforme necessário
