apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicejs-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicejs-a
  template:
    metadata:
      labels:
        app: servicejs-a
        version: "200"
    spec:
      containers:
      - name: servicejs-a
        image: abnerstelmastchuk/externalapi:2.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3100
---

apiVersion: v1
kind: Service
metadata:
  name: servicejs-a
spec:
  selector:
    app: servicejs-a
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3100
  type: LoadBalancer # Ou ClusterIP, NodePort, conforme necessário
